### PR TITLE
Fix pretty_print() indentation

### LINKED ISSUE #7: Pretty_print() indentation issue
Hi,

The function pretty_print() is checking for `)` and `),` lines to reduce indentation.
The thing is that some lines that should also be checked are `))` and `)),` so the indentation is fixed.

As you were careful to output the data according WPCS (e.g.: alignment of `=>` items), I suggest adding a linebreak before the array in `__set_state( array(`.

So, the solution is just to add a linebreak in both `(array(` and `))` strings and it's all set and fixed because you won't have anymore the `))` missing indentations! :)

Here is an example:
```
stdClass::__set_state(array(
	'updates' => array(
		stdClass::__set_state(array(
			'response' => 'development',
			'download' => 'https://wordpress.org/nightly-builds/wordpress-5.5-latest.zip',
			'locale' => 'en_US',
			'packages' => stdClass::__set_state(array(
				'full' => 'https://wordpress.org/nightly-builds/wordpress-5.5-latest.zip',
				'no_content' => '',
				'new_bundled' => '',
				'partial' => '',
				'rollback' => '',
				)),
				'current' => '5.5-RC2-48740',
				'version' => '5.5-RC2-48740',
				'php_version' => '5.6.20',
				'mysql_version' => '5.0',
				'new_bundled' => '5.3',
				'partial_version' => '',
				)),
				stdClass::__set_state(array(
					'response' => 'latest',
					'download' => 'https://downloads.wordpress.org/release/wordpress-5.4.2.zip',
					'locale' => 'en_US',
					'packages' => stdClass::__set_state(array(
						'full' => 'https://downloads.wordpress.org/release/wordpress-5.4.2.zip',
						'no_content' => 'https://downloads.wordpress.org/release/wordpress-5.4.2-no-content.zip',
						'new_bundled' => 'https://downloads.wordpress.org/release/wordpress-5.4.2-new-bundled.zip',
						'partial' => '',
						'rollback' => '',
						)),
						'current' => '5.4.2',
						'version' => '5.4.2',
						'php_version' => '5.6.20',
						'mysql_version' => '5.0',
						'new_bundled' => '5.3',
						'partial_version' => '',
						)),
						stdClass::__set_state(array(
							'response' => 'autoupdate',
							'download' => 'https://wordpress.org/nightly-builds/wordpress-5.5-latest.zip',
							'locale' => 'en_US',
							'packages' => stdClass::__set_state(array(
								'full'            => 'https://wordpress.org/nightly-builds/wordpress-5.5-latest.zip',
								'no_content'      => '',
								'new_bundled'     => '',
								'partial'         => '',
								'rollback'        => '',
								)),
								'current'         => '5.5-RC2-48740',
								'version'         => '5.5-RC2-48740',
								'php_version'     => '5.6.20',
								'mysql_version'   => '5.0',
								'new_bundled'     => '5.3',
								'partial_version' => '',
								'new_files'       => '1',
								)),
							),
							'last_checked' => 1596720174,
							'version_checked' => '5.5-RC2-48740',
							'translations' => array(),
							))
```

### PR DESCRIPTION
**Pull request by pedro-mendonca**
Fix #7 

Check the above issue for detailed description.

Add a linebreak in both `(array(` and `))` strings so `pretty_print()` can find the the currently closing `)),` lines and reduce indent correctly. It outputs valid WPCS code. :)

### CODE REVIEW

File: plugin.php [hunk 1]
```diff
@@ -871,7 +871,7 @@ public function render_tools_page() {
 			<div class='notice notice-warning inline'>
 				<p>
 						<?php
-						echo '<strong>' . esc_html__( 'Important', 'updates-api-inspector' ) . '</strong>:' .
+						echo '<strong>' . esc_html__( 'Important', 'updates-api-inspector' ) . '</strong>:&nbsp;' .
```
Comment (pbiron) [inline plugin.php]: Can you please break the 2 "string" changes out into a separate PR...so that this one is just about `pretty_print()`?

File: plugin.php [hunk 2]
```diff
@@ -957,7 +957,7 @@ public function render_tools_page() {
...
```
Comment (pbiron) [inline plugin.php]: Can you please break the 2 "string" changes out into a separate PR...so that this one is just about `pretty_print()`?

**Review by pbiron — CHANGES_REQUESTED** [review]

File: plugin.php (hunk 1 above)
Comment (pedro-mendonca) [reply plugin.php]: Sure, I'll remove these right away.

**Review by pbiron — CHANGES_REQUESTED** [review]
Can you please rebase this to `pbiron:develop`?  And then I'll merge.

After you opened this, I added #9, with a little info about PRs (I honestly didn't expect PRs so quickly and haven't yet gotten around to writing a `CONTRIBUTING.md` :-)

**Comment by pedro-mendonca** [comment]
> 
> 
> Can you please rebase this to `pbiron:develop`? And then I'll merge.
> 
> After you opened this, I added #9, with a little info about PRs (I honestly didn't expect PRs so quickly and haven't yet gotten around to writing a `CONTRIBUTING.md` :-)

Sure, done :)

**Review by pbiron — APPROVED** [review]
Thank you!

Not only does this help with PHP < 7.3, but also when the request to the API returns a `WP_Error`.
